version: '3.1'

services:

  postgres:
    image: postgres:16.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=sakila
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
